### PR TITLE
Allow users to instantiate ServerSocket themselves

### PR DESCRIPTION
**Pull request by alexarchambault**
This PR allows users to pass their own `java.net.ServerSocket` instance for domain sockets, rather than letting nailgun build it with its `NGUnixDomainServerSocket` and `NGWin32NamedPipeServerSocket` classes.

The should allow Bloop to get its `ServerSocket` instance via [libdaemon-jvm](https://github.com/alexarchambault/libdaemon-jvm), that
- can build those instances via JDK 16 native support for domain sockets, which should be more reliable than using JNA
- ensures such a server socket is created and listened on by only one process at a time, relying on file locks, among others, to do so.

(Feel free to either merge right now, or wait for the upcoming Bloop PR that relies on this.)

### CODE REVIEW

**Comment by alexarchambault** [comment]
cc @tgodzik

**Comment by tgodzik** [comment]
I think these changes look sensible, we should merge it (I think I should have the rights now, but you might need to make it ready to review)

btw. @alexarchambault do you think we could upstream the changes here to the main fork of nailgun? I haven't looked too much into this fork, but it would be awesome to get rid of it.

**Comment by alexarchambault** [comment]
@tgodzik Let's merge if it's fine then. Not sure if that's published once it's merged though, it seems there's no CI any more :/

**Comment by alexarchambault** [comment]
About upstreaming the changes here, I'm not really sure. It seems the changes revolve around:
- logging and some extra `NGServer` constructors (https://github.com/scalacenter/nailgun/commit/8f005946a89ad11b9dd569c034a08b7e04f123e1)
- more logging changes (https://github.com/scalacenter/nailgun/commit/ee3c4343801c48b525ffa448895fd95f7216ce3c)
- disabling the security manager stuff (https://github.com/scalacenter/nailgun/commit/10c004d5) - discussed in https://github.com/facebook/nailgun/issues/134 apparently
- plus the changes of this PR

**Comment by alexarchambault** [comment]
About the logging-related changes, I'm inclined to think these are unnecessary… Bloop could just configure java.util.logging on its own, rather than switching the codebase here to slf4j. If we really want logging messages via slf4j, we can always use a java-util-logging-to-slf4j bridge. But it seems Bloop disables those messages altogether via slf4j-nop, so we might as well just disable them by configuring java.util.logging (can even be done via some API calls IIRC).

**Comment by alexarchambault** [comment]
That leaves:
- extra `NGServer` constructors for custome stdin / stdout / stderr (no idea if that would be welcomed upstream)
- security manager stuff (maybe we could insist in https://github.com/facebook/nailgun/issues/134)
- custom `ServerSocket` instance (this PR, no idea if that would be welcomed upstream either)

**Comment by tgodzik** [comment]
> That leaves:
> 
> * extra `NGServer` constructors for custome stdin / stdout / stderr (no idea if that would be welcomed upstream)
> * security manager stuff (maybe we could insist in [Overhead of SecurityManager facebook/nailgun#134](https://github.com/facebook/nailgun/issues/134))
> * custom `ServerSocket` instance (this PR, no idea if that would be welcomed upstream either)

From what I see the maintainers do not seem too active there, so maybe it's ok to leave this fork be.

**Comment by tgodzik** [comment]
For releasing I think it was done manually :thinking:  I need to figure out who can be bothered to do it :sweat_smile:

**Pull request merged**
